# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kamitsui <kamitsui@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/29 19:48:01 by kamitsui          #+#    #+#              #
#    Updated: 2023/09/02 15:12:56 by kamitsui         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Target name
NAME1 = run.sh
NAME2 = run_checker_Mac.sh

# Run Target
RUN1 = ./$(NAME1) ; echo "\n\n"
RUN2 = ./$(NAME2) ; echo "\n\n"

all :
	$(RUN1)
	$(RUN2)

1 :
	$(RUN1)
2 :
	$(RUN2)

.PHONY: all 1 2
