# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kamitsui <kamitsui@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/29 19:48:01 by kamitsui          #+#    #+#              #
#    Updated: 2023/09/04 20:19:51 by kamitsui         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Target name
NAME1 = variable_test.sh
NAME2 = Err_has_Duplicates.sh
NAME3 = less_than_seven_elements.sh

# Run Target
RUN1 = ./$(NAME1) ; echo "\n\n"
RUN2 = ./$(NAME2) ; echo "\n\n"
RUN3 = ./$(NAME3) ; echo "\n\n"

all :
	$(RUN1)
	$(RUN2)
	$(RUN3)

1 :
	$(RUN1)
2 :
	$(RUN2)
3 :
	$(RUN3)

.PHONY: all 1 2 3
